version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: qwipo_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: qwipo_ai
    volumes:
      - mongodb_data:/data/db
    networks:
      - qwipo_network

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: qwipo_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - qwipo_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: qwipo_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/qwipo_ai
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=qwipo-ai-secret-key-2024
      - FLASK_ENV=production
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend:/app
    networks:
      - qwipo_network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: qwipo_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - qwipo_network

volumes:
  mongodb_data:
  redis_data:

networks:
  qwipo_network:
    driver: bridge

